### PR TITLE
refactor(tasks/codecov): remove custom config

### PR DESCRIPTION
**Pull request by michael-ciniawsky**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
> Why? It is not good when after PR coverage very decrease?

How does this config influence that ? What does it add to set it up this way instead of using 'the defaults'?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky How we can setup this without config? :confused: Don't find docs about this.

**Comment by michael-ciniawsky** [comment]
I'm under the impression we don't _really_ need to setup anything here as the coverage reporting 'just works'  normally. I'm not 💯 sure what the current custom confg does (provides us) atm

**Comment by evilebottnawi** [comment]
@michael-ciniawsky this config require to send PR more tests, if converge is less than the required value, I think it's good, since it will make us write fewer messages `Please add tests`

**Comment by michael-ciniawsky** [comment]
> For me comments should not increase/decrease coverage?

I think this refers to the codecov comment being added to the PR thread (Y/n). I just grouped it wrong in the comment above will update :)

**Pull request merged**
