### PR TITLE
feat(dotfile): add .editorconfig to templates

### PR DESCRIPTION
**Pull request by shellscape**
This PR adds `.editorconfig` to the `templates`. This is a relatively standard file now, and curiously it's existed for some time in this repo but never made it into `templates`.

### CODE REVIEW

**Comment by d3viant0ne** [comment]
https://github.com/webpack-contrib/webpack-defaults/blob/master/src/tasks/editorconfig.js

**Comment by shellscape** [comment]
Odd. It didn't place that file when I ran it on restyle earlier today. Do we need the js generation when a static file will do?

**Comment by d3viant0ne** [comment]
For the `.editorconfig` not really but it needs to be one other the other. 

Either convert it to a template & remove the task that executes `editorconfig.js` or leave it as is.

**Comment by shellscape** [comment]
Removed the generator task in favor of the static template.

**Pull request merged**
