### PR TITLE
chore: improve bin name, issue templates, line endings, editorconfig

### PR DESCRIPTION
**Pull request by shellscape**
Fixes the name of the bin that the post-install script sets up for the `defaults` package script.

### CODE REVIEW

**Comment by shellscape** [comment]
@ooflorent there's no need `"bin": "bin/index.js",` is sufficient and will use the package's name. it's been that way for over a year.

**Comment by ooflorent** [comment]
@shellscape Yes it was, but is wasn't using a namespace. Making it explicit would be better and would have avoid this PR.

**Comment by shellscape** [comment]
Well I don't think it would have avoided the PR. The script injection is still a manual step, and the name still would have diverged from the package name change. Seems six of one, half dozen of another. I actually prefer the dynamic `bin` name, as it's one less thing to maintain.

**Comment by shellscape** [comment]
@ooflorent please give this another look. your suggestion was implemented :)

**Pull request merged**
