### PR TITLE
feat - Write webpack-defaults script on initial install

### LINKED ISSUE #11: Installing webpack-defaults should write webpack-defaults script to run?
If you use webpack-defaults, you have to write the script anyhow so maybe it makes sense to write `"webpack-defaults": "webpack-defaults"` to `scripts`.

Any thoughts?

### PR DESCRIPTION
**Pull request by bebraw**
* The way it figures out the project path can likely be improved.
* To fix `post_install`, I had to stub `dist/index.js` (versioned in the project). You have to be careful not to override that.

Closes #11.

### CODE REVIEW

**Comment by bebraw** [comment]
To fix Travis, you probably have to enable `Failing Criteria` at https://www.bithound.io/settings/github/webpack-contrib/webpack-defaults/integrations . For some reason it didn't save the setting for me.

**Comment by sapegin** [comment]
Same for me: “Oh no! There appears to be a problem with saving this setting”.

**Comment by bebraw** [comment]
Ok, I'll poke them.

**Comment by d3viant0ne** [comment]
It has done that for more than a day. Something in their system is throwing a 500 ( uthoh ).

At this point, imo it's time to temporarily disable it until they sort things out.

**Pull request merged**
