### PR TITLE
fix(.babelrc): enable modules

### PR DESCRIPTION
**Pull request by michael-ciniawsky**

### CODE REVIEW

**Comment by simnalamburt** [comment]
This Pull Requested will cause the built-in Tree Shaking feature to stop working. Why was this Pull Request created?

**Comment by sapegin** [comment]
@simnalamburt Why do you need tree shaking for webpack loaders and plugins?

**Comment by michael-ciniawsky** [comment]
For loaders this could be disabled as the are 'processed' by webpack, plugins still need to be transpiled as they are normal NodeJS Modules (CommonJS). In any case `tree-shaking` is not required or beneficial here. There is no limitation in file size or network connection

**Comment by simnalamburt** [comment]
Oh I see. I had no idea since there were no description in the PR or commit message. Does https://github.com/webpack-contrib/webpack-defaults/commit/f85ac124fb52e5ef217f1afe14af40368cea8365 have the same purpose?

**Comment by michael-ciniawsky** [comment]
[f85ac12](https://github.com/webpack-contrib/webpack-defaults/commit/f85ac124fb52e5ef217f1afe14af40368cea8365)  enabled module transpilation for the reason mentioned in my last comment 😛  It makes no difference for loaders and `webpack-defaults` is used for both

**Pull request merged**
