### PR TITLE
feat(tasks): add `codecov.yml`

### PR DESCRIPTION
**Pull request by hulkish**

### CODE REVIEW

**Comment by sapegin** [comment]
I can’t say anything about the contents of the `codecov.yml` but otherwise looks good ;-)

**Comment by michael-ciniawsky** [comment]
Yep we need to triage necessity 😉 , but seems to be needed in `uglifyjs-webpack-plugin`

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - There was a discussion via email around this topic between @bebraw & Codecov.io.

The desire is to limit the pull request checks to what is really `of value` as opposed to patch + project + branch coverage checks.

**Comment by d3viant0ne** [comment]
It's more of a quality of life addition so codecov doesn't try to run every check on the planet for a PR.

I'm good with it as is, we can always refine later if we want.

**Pull request merged**
