### PR TITLE
chore(package): update dependencies

### PR DESCRIPTION
**Pull request by michael-ciniawsky**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
[`updtr`](https://github.com/peerigon/updtr) ?

**Comment by d3viant0ne** [comment]
Yeah, thought there was an issue for that already. Original request was greenkeeper.io which we aren't going to do.

**Comment by d3viant0ne** [comment]
The sanest approach may to control the versions installed with defaults ( patch range ) and roll the deps updates out like any other defaults update we have done recently.

**Comment by michael-ciniawsky** [comment]
Closing this as it is outdated now :)

**Pull request closed without merging**
