### PR TITLE
refactor: remove default build step (via `babel`)

### LINKED ISSUE #126: Remove default build step (via babel)
Remove the build step via `babel` by default so it is possible to add it on demand for repos that _really_ need it instead o adding it by default for every repo (We just don't handle this via `webpack-defaults` anymore)

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
### Issues

- Fixes #126

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
This is not about using no transpilation at all, but to not included it be default anymore (Set it up yourself if needed). Many repos don't really need

**Comment by michael-ciniawsky** [comment]
Alternatively we could try to tackle #87 and add a flag (e.g `webpack-defaults --task build`)  to set it up for repos which need transpiling

**Comment by evilebottnawi** [comment]
@michael-ciniawsky :+1: on `flag`, maybe better `--transpiling` flag?

**Comment by michael-ciniawsky** [comment]
kk I open a PR to add a general small CLI Interface and one for `babel` in particular afterwards, a `webpack-defaults (init) --loader/--plugin` flag would also be good to have (also separate PR)

**Pull request closed without merging**
